sonobuoy-config:
  driver: Job
  plugin-name: e2efanout
  result-format: junit
spec:
  command:
  - ./run.sh
  env:
  - name: NUM_BUCKETS
    value: "3"
  image: sonobuoy/e2efanout:v0
  name: plugin

